### ISSUE TITLE
ESI: multiple questions

### ISSUE THREAD

**Issue by gpluess** [barryvdh/laravel-httpcache#2]
I have a website that consists of mainly user generated content. To speed things a little bit up I started to play around with this package.

Enabling cache brings the response time from ~600ms down to ~80ms on my local Vagrant box, which is great! However, there are small parts in the navigation that should never be cached, like the login button / profile link (in case the user is logged in) and other navigation elements.

So here are my beginner questions:

1) I made a partial view and included it with ESI and set the cache time to 0. The page content is cached except for the login stuff. This seemed to work. But is this the right way to do that?

2) Is invalidating the cache possible with this package? I want the cache to be refreshed when a new "item" is submitted by a user, but otherwise cache that page with all items on it as long as possible.

3) Is it an issue when the above mentioned ESI fragments are publicly accessible (in a browser for example)? There is a trusted proxies setting in Symfony. Would that render those URLs protected for direct Browser access?

Thanks a lot for your help in advance!

**Comment by barryvdh** [comment]
Hey,

short answer:
1. Yes you should probably just set the partial response headers to private/no cache.
2. You can purge specific pages/routes: http://symfony.com/doc/current/book/http_cache.html#cache-invalidation or use `App::make('http_cache.store')->purge($url);`
3. Trusted proxies is for allowing certain proxies (like varnish) to pass on the IP of the original client, so not sure if that's the case. Symfony has some main/sub request things, but not sure if that works in Laravel. But the parts that are available are probably already visible right? You could protect them with user auth as usual I guess. (And they would see the route to the esi part usual, but that's just obscurity)

But I'm not an expert in these ESI stuff, just used it for a simple project. It's almost completely just the Symfony http cache so if you can find info on that, you could use most of it in here.

And remember that Varnish is usually a better option, if at all possible. It also offers ESI stuff in a similar way, but caches in memory instead of a file-store (or different store)

**Comment by gpluess** [comment]
Barry, thanks for your explanation!

One more question addressing your last sentence: is there a way to use memcached instead of a file-store? I'd prefer not to use Varnish. I'm not that experienced with backend / server stuff, so I'd like to avoid that and keep things simple.

**Comment by barryvdh** [comment]
I'm not sure. There are alternative caches, but not provided by default, which implement the StoreInterface.

https://github.com/bamarni/symfony-http-cache-extension uses Doctrine Cache (which has Memcached etc)
https://github.com/solilokiam/HttpRedisCache is a Redis Store

I guess it would also be possible to create a Laravel Cache store so you can use the Laravel cache system..

**Comment by gpluess** [comment]
Thanks a lot for your comment, I really appreciate it!
